/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        blue: '#5C8AF0',
        'blue-2': '#5D8AE8',
        'blue-deep': '#0F44A7',
        cream: '#FFFBED',
        'gray-blue': '#D6DFEE',
        coral: '#FF7A7A',
        orange: '#FFB974',
        'orange-deep': '#F0912F',
        yellow: '#FFE374',
        red: '#FF0000',
        ink: '#1E1E1E',
        'ink-2': '#3C4457',
        'ink-3': '#5A6272',
        'ink-4': '#7C8494',
        'ink-5': '#9AA0AE',
        'tag-pink': '#FFEAF5',
        'tag-green': '#C9FFC0',
        'tag-blue': '#D6DFEE',
        'border-light': '#EEF1F6',
        'border-soft': '#E1E5EE',
        'tabbar-bg': '#F3F4F8',
      },
      fontFamily: {
        sans: [
          '-apple-system',
          'BlinkMacSystemFont',
          '"PingFang SC"',
          '"Helvetica Neue"',
          '"Microsoft YaHei"',
          'sans-serif',
        ],
      },
      borderRadius: {
        card: '16px',
        'card-sm': '14px',
        'card-xs': '12px',
        btn: '20px',
        'btn-sm': '19px',
        tag: '6px',
      },
      boxShadow: {
        card: '0 3px 14px rgba(40,70,140,0.10)',
        'card-sm': '0 2px 10px rgba(40,70,140,0.09)',
        'btn-primary': '0 4px 14px rgba(92,138,240,0.34)',
        'top-sheet': '0 -3px 18px rgba(40,70,140,0.08)',
        avatar: '0 3px 12px rgba(30,50,110,0.18)',
      },
      keyframes: {
        'dot-bounce': {
          '0%, 80%, 100%': { transform: 'translateY(0)', opacity: '0.55' },
          '40%': { transform: 'translateY(-4px)', opacity: '1' },
        },
        'rise-in': {
          from: { opacity: '0', transform: 'translateY(12px)' },
          to: { opacity: '1', transform: 'none' },
        },
        'fade-in': {
          from: { opacity: '0' },
          to: { opacity: '1' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-3px)' },
        },
        'bean-idle': {
          '0%,100%': { transform: 'rotate(-1.5deg) translateY(0)' },
          '50%': { transform: 'rotate(1.5deg) translateY(-4px)' },
        },
        'bean-shake': {
          '0%': { transform: 'translate(0,0) rotate(0)' },
          '15%': { transform: 'translate(-8px,3px) rotate(-8deg)' },
          '30%': { transform: 'translate(7px,-4px) rotate(7deg)' },
          '45%': { transform: 'translate(-7px,3px) rotate(-6deg)' },
          '60%': { transform: 'translate(6px,-2px) rotate(5deg)' },
          '75%': { transform: 'translate(-4px,1px) rotate(-3deg)' },
          '100%': { transform: 'translate(0,0) rotate(0)' },
        },
        'bean-listening': {
          '0%': { transform: 'translate(0,0) rotate(0)' },
          '15%': { transform: 'translate(-5px,2px) rotate(-5deg)' },
          '30%': { transform: 'translate(5px,-3px) rotate(5deg)' },
          '45%': { transform: 'translate(-4px,2px) rotate(-4deg)' },
          '60%': { transform: 'translate(3px,-1px) rotate(3deg)' },
          '75%': { transform: 'translate(-2px,1px) rotate(-2deg)' },
          '100%': { transform: 'translate(0,0) rotate(0)' },
        },
        'burst-out': {
          from: { transform: 'translate(-50%,-50%) scale(1)', opacity: '1' },
          to: { transform: 'translate(var(--bx,0),var(--by,0)) scale(.2)', opacity: '0' },
        },
      },
      animation: {
        'dot-bounce': 'dot-bounce 1.05s ease-in-out infinite',
        'rise-in': 'rise-in 0.35s ease-out both',
        'fade-in': 'fade-in 0.25s ease-out both',
        float: 'float 3s ease-in-out infinite',
        'bean-idle': 'bean-idle 2.4s ease-in-out infinite',
        'bean-shake': 'bean-shake .4s cubic-bezier(.36,.07,.19,.97) infinite',
        'bean-listening': 'bean-listening .5s ease-in-out infinite',
        'burst-out': 'burst-out .7s ease-out forwards',
      },
      transitionTimingFunction: {
        spring: 'cubic-bezier(0.34,1.56,0.64,1)',
      },
    },
  },
  plugins: [],
};
